### ISSUE TITLE
how update widget  every 15 min

### ISSUE THREAD

**Issue by jafarpishdadi** [gaetanozappi/react-native-widget-listview#1]
hello
thanks for release this package

I want the data to be called from the url in widgttask.js every 15 minutes

onupdate in  WidgetProvider is called every 30 minutes but the data not updated 
how to set when onupdate called  widgetTask run Again
thanks

**Comment by gaetanozappi** [comment]
Hi @jafarpishdadi :

A long time since I started this project again, I tried to change the value of android: `updatePeriodMillis="90000000"`
with
`Android: updatePeriodMillis="900000"`

File: [Widgetprovider](https://github.com/gaetanozappi/react-native-widget-listview/blob/master/android/app/src/main/res/xml/widgetprovider.xml#L5)

**Comment by jafarpishdadi** [comment]
thanks for replay
onupdate called and no problem 
but data data not updated
https://github.com/gaetanozappi/react-native-widget-listview/blob/master/widgetTask.js
I want the data to be called from the url in widgttask.js every 15 minutes
this section not run
bgTimer.setTimeout(() => {
    fetch('https://www.simplifiedcoding.net/demos/marvel/')
    .then((response) => response.json())
    .then((responseJson) => {
      synchronizeWidget(responseJson)
    }).catch((error) => {
      console.error(error);
    });
  }, 0)

**Comment by gaetanozappi** [comment]
@jafarpishdadi :

Try doing this in `widgetTask.js`:

```
bgTimer.setInterval(() => {
    fetch('https://www.simplifiedcoding.net/demos/marvel/')
    .then((response) => response.json())
    .then((responseJson) => {
      synchronizeWidget(responseJson)
    }).catch((error) => {
      console.error(error);
    });
  }, 900000);
```

**Comment by jafarpishdadi** [comment]
thanks  @gaetanozappi 

im use setinterval  code
in background data receive after 15 min and Continue to 15 minutes
but when app close data not receive and stop widget

 log onupdate function in   WidgetProvider 
this called every 15 minutes but not receive data from widgettask

How to manually update task with  refresh-icon ?

**Comment by gaetanozappi** [comment]
@jafarpishdadi : 

With a video or with a more detailed explanation point by point it would be easier to understand what really happens and what you would like to do.

Consider that it is only a trial version of a module widget, since there is not much information and documentation about it at the moment about these bridge experiments, especially at the time of what was in development a year ago.

At the moment I don't have the equipment and the time to be able to help you adequately.

Take a look at this project, in particular the following files:

- [AndroidManifest.xml#L29](https://github.com/Angelk90/WidgetAndroid/blob/dd95db0409cdec585c6f6b9819e83a8f0d365e01/app/src/main/AndroidManifest.xml#L29)

- [widget.xml#L54](https://github.com/Angelk90/WidgetAndroid/blob/dd95db0409cdec585c6f6b9819e83a8f0d365e01/app/src/main/res/layout/widget.xml#L54)

- [ListWidgetProvider.java#L28](https://github.com/Angelk90/WidgetAndroid/blob/dd95db0409cdec585c6f6b9819e83a8f0d365e01/app/src/main/java/com/widgettwitter/tweet/ListWidgetProvider.java#L28)

- [ListWidgetProvider.java#L69](https://github.com/Angelk90/WidgetAndroid/blob/dd95db0409cdec585c6f6b9819e83a8f0d365e01/app/src/main/java/com/widgettwitter/tweet/ListWidgetProvider.java#L69)

- [ListWidgetProvider.java#L113](https://github.com/Angelk90/WidgetAndroid/blob/dd95db0409cdec585c6f6b9819e83a8f0d365e01/app/src/main/java/com/widgettwitter/tweet/ListWidgetProvider.java#L113)

- [ListWidgetViewsFactory.java#L97](https://github.com/Angelk90/WidgetAndroid/blob/dd95db0409cdec585c6f6b9819e83a8f0d365e01/app/src/main/java/com/widgettwitter/tweet/ListWidgetViewsFactory.java#L97)

It might give you some suggestions on how to create a refresh button manually to get the data.

Surely on stackoverflow they will be able to help you much better than me, there are lots of very experienced Android developers, try asking them for some suggestions.

**Comment by creativemind1** [comment]
I have also faced similar issues some times back with the widget. But unfortunately I've not worked further after that because there's no suffcient documentation available for this. I'd definitely like to assist you.
1. Have you tried https://stackoverflow.com/questions/39946431/what-is-the-best-way-to-schedule-a-task-in-react-native ?
Not sure what is your purpose for updating widget every 15 minute as you are fetching data from the API, so widget must update it dynamically from API, isn' it?

**Comment by jafarpishdadi** [comment]
hi @creativemind1 
Thanks for your help

im design weather widget for app that update every 15 minute 
i would to fetch data from url and update widget

**Comment by creativemind1** [comment]
> hi @creativemind1
> Thanks for your help
> 
> im design weather widget for app that update every 15 minute
> i would to fetch data from url and update widget

Do you have any proper repo to check and comment?
